function f = ode(t,x,O)
% f = Decoy.ODE.ode(t,x,O) includes the differential equations extracted
% from model struct O.
% O can be generated by Decoy.ODE.initialize()
% The output of this ode is:

f = zeros(O.info.species,1);

f(O.species.T) = f(O.species.T) + x(O.species.TN)*O.values(O.parameters.Knmin) - x(O.species.N)*x(O.species.T)*O.values(O.parameters.Knplus);
f(O.species.N) = f(O.species.N) + x(O.species.TN)*O.values(O.parameters.Knmin) - x(O.species.N)*x(O.species.T)*O.values(O.parameters.Knplus);
f(O.species.TN) = f(O.species.TN) - x(O.species.TN)*O.values(O.parameters.Knmin) + x(O.species.N)*x(O.species.T)*O.values(O.parameters.Knplus);


f(O.species.T) = f(O.species.T) + x(O.species.TP)*O.values(O.parameters.Kpmin) - x(O.species.P)*x(O.species.T)*O.values(O.parameters.Kpplus);
f(O.species.P) = f(O.species.P) + x(O.species.TP)*O.values(O.parameters.Kpmin) - x(O.species.P)*x(O.species.T)*O.values(O.parameters.Kpplus);
f(O.species.TP) = f(O.species.TP) - x(O.species.TP)*O.values(O.parameters.Kpmin) + x(O.species.P)*x(O.species.T)*O.values(O.parameters.Kpplus);

f(O.species.T) = f(O.species.T) + x(O.species.PT)*O.values(O.parameters.Kpmin) - x(O.species.P)*x(O.species.T)*O.values(O.parameters.Kpplus);
f(O.species.P) = f(O.species.P) + x(O.species.PT)*O.values(O.parameters.Kpmin) - x(O.species.P)*x(O.species.T)*O.values(O.parameters.Kpplus);
f(O.species.PT) = f(O.species.PT) - x(O.species.PT)*O.values(O.parameters.Kpmin) + x(O.species.P)*x(O.species.T)*O.values(O.parameters.Kpplus);

f(O.species.T) = f(O.species.T) + x(O.species.TPT)*O.values(O.parameters.Kpmin) - x(O.species.TP)*x(O.species.T)*O.values(O.parameters.Kpplus);
f(O.species.TP) = f(O.species.TP) + x(O.species.TPT)*O.values(O.parameters.Kpmin) - x(O.species.TP)*x(O.species.T)*O.values(O.parameters.Kpplus);
f(O.species.TPT) = f(O.species.TPT) - x(O.species.TPT)*O.values(O.parameters.Kpmin) + x(O.species.TP)*x(O.species.T)*O.values(O.parameters.Kpplus);

f(O.species.T) = f(O.species.T) + x(O.species.TPT)*O.values(O.parameters.Kpmin) - x(O.species.PT)*x(O.species.T)*O.values(O.parameters.Kpplus);
f(O.species.PT) = f(O.species.PT) + x(O.species.TPT)*O.values(O.parameters.Kpmin) - x(O.species.PT)*x(O.species.T)*O.values(O.parameters.Kpplus);
f(O.species.TPT) = f(O.species.TPT) - x(O.species.TPT)*O.values(O.parameters.Kpmin) + x(O.species.PT)*x(O.species.T)*O.values(O.parameters.Kpplus);

f = f(:);

end