function f = ode(t,x,O)
% f = Decoy.ODE.ode(t,x,O) includes the differential equations extracted
% from model struct O.
% O can be generated by Decoy.ODE.initialize()
% The output of this ode is:
% 1 - T0
% 2 - T
% 3 - N
% 4 - TN
% 5 - N0
% 6 - P
% 7 - TP
% 8 - P0

f(1:O.info.species) = 0;
for i = 1:O.info.reactions
    f(O.reactions(i).reactant) = f(O.reactions(i).reactant) - prod(x(O.reactions(i).reactant))*O.rates(i).megaRatePlus + prod(x(O.reactions(i).product))*O.rates(i).megaRateMin;
    f(O.reactions(i).product) = f(O.reactions(i).product) - prod(x(O.reactions(i).product))*O.rates(i).megaRateMin + prod(x(O.reactions(i).reactant))*O.rates(i).megaRatePlus;
end
f = f(:);

end