function M = initialize()
% [D,F,M] = MERGED.ODE.INITIALIZE() generates the data for master ode model
% D - the data of decoy model, generated by Decoy.ODE.initialize(), to be
% used in Merged.ODE.ode
% F - the data of FNR model, generated by FNR.ODE.initialize(), to be used
% in Merged.ODE.ode
% M - the data of master model, to be used in Tools.steadystate
% the structure of M looks like this:
% M
%   .info
%       .model                              - 'master'
%   .Decoy                                  - Decoy struct
%   .FNR                                    - FNR struct
%   .amounts(id)                            - initial concentrations
%   .oxygen                                 - oxygen concentrations

D = Decoy.ODE.initialize();
F = FNR.ODE.initialize();

M.info.model = 'Merged';
M.info.species = 10;

d('------ Species ------');
M.species = D.species;

M.species.toName(9) = 'FNR mRNA';
M.species.toID('FNR mRNA') = 9;
d('- Added species `FNR-mRNA`');

M.species.toName(10) = 'Inactive FNR';
M.species.toID('Inactive FNR') = 10;
d('- Added species `Inactive FNR`');

M.Decoy = D;
M.FNR = F;

M.amounts = D.amounts;
M.amounts(2) = F.amounts(3);
M.amounts(9) = F.amounts(1);
M.amounts(10) = F.amounts(2);
M.amounts(1) = sum(M.amounts([2 4 7]));

M.oxygen = 0;

end